### ISSUE TITLE
BSC snapshot downloading stuck at 99%

### ISSUE THREAD

**Issue by yiteng-guo** [ledgerwatch/erigon-snapshot#2]
Hi, I'm trying to sync a erigon-bsc node but it gets stuck at 99.79%.
```
[Snapshots] download                     progress=99.79% download="0 B/s"
```
I started the downloading at this commit 4be4e5b99 in erigon repo. After getting stuck a day, I built the binary at this commit `cedb4865c` (latest devel) but it's still stuck at 99.79%.

**Comment by AskAlexSharov** [comment]
seems very old issue, closing
